services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - default

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8080:8080"
    networks:
      - default

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    networks:
      - default

networks:
  default:
